config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :photos
  resources :galleries
  resources :nightclubs do
    resources :galleries
  end
  get '/my_nightclubs' => 'nightclubs#my_nightclubs'
  resources :questions
  resources :home
  get '/adapted_nightclubs' => 'nightclubs#adapted', :as => :adapted
  match '/home' => 'home#index', via: [:get, :post]
  get 'events' => 'home#events'
  get '/photography' => 'photography#index'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :gallery, required: true
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200", thumbnail: "171x180"}
  validates_attachment_file_name :image, matches: [/png\z/, /jpe?g\z/]

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo.gallery.nightclub, notice: 'Imagen añadida con éxito, ' }
        format.json { render :show, status: :created, location: @photo.gallery.nightclub }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:gallery_id, :image)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(photo) do |f| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gallery_id %>
    <%= f.text_field :gallery_id %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, :required => true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th>Gallery</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.gallery %></td>
        <td><%= photo.image %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gallery:</strong>
  <%= @photo.gallery %>
</p>

<p>
  <strong>Image:</strong>
  <%= @photo.image %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>