config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :photos
  resources :galleries
  resources :nightclubs do
    resources :galleries
  end
  get '/my_nightclubs' => 'nightclubs#my_nightclubs'
  resources :questions
  resources :home
  get '/adapted_nightclubs' => 'nightclubs#adapted', :as => :adapted
  match '/home' => 'home#index', via: [:get, :post]
  get 'events' => 'home#events'
  get '/photography' => 'photography#index'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/nightclub.rb
class Nightclub < ApplicationRecord
  belongs_to :user #representante del local en la página
  has_many :galleries

  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200", thumbnail: "171x180"}
  validates_attachment_file_name :image, matches: [/png\z/, /jpe?g\z/]

  scope :adapted, -> { where(adapted: true) }
  scope :no_adapted, -> { where(adapted: false) }
end

app/controllers/nightclubs_controller.rb
class NightclubsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_nightclub, only: [:show, :edit, :update, :destroy]

  # GET /nightclubs
  # GET /nightclubs.json
  def index
    @nightclubs = Nightclub.all
  end

  # GET /nightclubs/1
  # GET /nightclubs/1.json
  def show
    @gallery_and_photo = [Gallery.new, Photo.new]
  end

  # GET /nightclubs/new
  def new
    @nightclub = Nightclub.new
  end

  def adapted
    @adaptedclubs = Nightclub.adapted
  end


  # GET /nightclubs/1/edit
  def edit
  end

  # POST /nightclubs
  # POST /nightclubs.json
  def create
    @nightclub = Nightclub.new(nightclub_params)

    respond_to do |format|
      if @nightclub.save
        format.html { redirect_to @nightclub, notice: 'Local creado exitosamente, ' }
        format.json { render :show, status: :created, location: @nightclub }
      else
        format.html { render :new }
        format.json { render json: @nightclub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nightclubs/1
  # PATCH/PUT /nightclubs/1.json
  def update
    respond_to do |format|
      if @nightclub.update(nightclub_params)
        format.html { redirect_to @nightclub, notice: 'Local actualizado exitosamente, ' }
        format.json { render :show, status: :ok, location: @nightclub }
      else
        format.html { render :edit }
        format.json { render json: @nightclub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nightclubs/1
  # DELETE /nightclubs/1.json
  def destroy
    if @nightclub.user != current_user
      @nightclub.destroy
      respond_to do |format|
        format.html { redirect_to my_nightclubs_path, notice: 'Local destruido exitosamente, ' }
        format.json { head :no_content }
      end
    else
      redirect_to my_nightclubs_path, notice: 'No tienes permisos para destruir el local, '
    end
  end

  # GET /my_nightclubs
  def my_nightclubs
    @nightclubs = Nightclub.where(user_id: current_user.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nightclub
      @nightclub = Nightclub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nightclub_params
      params.require(:nightclub).permit(:user_id, :name, :price, :location, :description, :date,
                                        :validity, :adapted, :image, :latitude, :longitude)
    end
end

app/helpers/nightclubs_helper.rb
module NightclubsHelper
end

app/views/nightclubs/_form.html.erb
<%= form_for(nightclub) do |f| %>
    <% if nightclub.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(nightclub.errors.count, "error") %> prohibited this nightclub from being saved:</h2>

          <ul>
            <% nightclub.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field hidden">
      <%= f.label :user_id %>
      <%= f.text_field :user_id, :required => true, value: current_user.id %>
    </div>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, :required => true, class: "black-text" %>
    </div>

    <div class="field">
      <%= f.label :price %>
      <%= f.text_field :price, :required => true, class: "black-text" %>
    </div>

    <div class="field">
      <%= f.label :location %>
      <%= f.text_field :location, :required => true, class: "black-text" %>
    </div>

    <div class="field">
      <%= f.label :latitude %>
      <%= f.text_field :latitude, :required => true, class: "black-text" %>
    </div>

    <div class="field">
      <%= f.label :longitude %>
      <%= f.text_field :longitude, :required => true, class: "black-text" %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description, :required => true, class: "black-text" %>
    </div>

    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image, :required => true %>
    </div>

    <div class="field">
      <%= f.label :date %>
      <div class="black-text"><%= f.date_select :date, class: "black-text" %></div>
    </div>

    <div class="field">
      <%= f.label :validity %>
      <div class="black-text"><%= f.date_select :validity %></div>
    </div>

    <div class="field">
      <%= f.label :adapted %>
      <%= f.check_box :adapted, class: "black-text" %>
    </div>

    <div class="actions black-text">
      <%= f.submit %>
    </div>
<% end %>

app/views/nightclubs/_gallery_form.html.erb
<%= form_for(gallery) do |f| %>
  <% if gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field hidden">
    <%= f.label :nightclub_id %>
    <%= f.text_field :nightclub_id, value: @nightclub.id %>
  </div>

  <div class="actions">
    <%= f.submit " Añadir galería", class: "btn btn-default glyphicon glyphicon-plus" %>
  </div>
<% end %>

app/views/nightclubs/_map.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyAND5z9Tbkt3FkhDNLprNfnFNfH2l0bnGo"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

<div id="map"></div>
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": <%= @nightclub.latitude %>,
        "lng": <%= @nightclub.longitude %>,
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/nightclubs/_photo_form.html.erb
<%= form_for(photo) do |f| %>
    <% if photo.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

          <ul>
            <% photo.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field hidden">
      <%= f.label :gallery_id %>
      <%= f.text_field :gallery_id, value: gallery_id %>
    </div>

    <div class="field hidden">
      <%= f.label :image %>
      <%= f.file_field :image, :required => true, id: "trigger#{gallery_id}" %>
    </div>

    <button id="button<%= gallery_id %>" type="button" class="btn btn-default">
      <span class="glyphicon glyphicon-picture"> Examinar...</span>
    </button>

    <div class="actions black-text">
      <%= f.submit "Añadir foto" %>
    </div>
<% end %>

<script>
  $(document).ready(function () {
    $('#button<%= gallery_id %>').on('click', function (e) {
      e.preventDefault();
      $("#trigger<%= gallery_id %>").trigger('click');
    });
  });
</script>

app/views/nightclubs/adapted.html.erb
<!-- Carousel-->
<div class="carousel-container col-md-8 col-md-offset-2" >
  <%=  render 'layouts/carousel' %>
</div>

<div class="nav-wrapper">
  <div id="affix-container" class="row spacing-navbar  clear myaffix nav" data-spy="affix">
    <%= render 'layouts/navbar' %>
  </div>
</div>

<div id="container" class="clear">
  <% @adaptedclubs.each do |nightclub| %>
      <div class="grid col-md-2 col-md-offset-1">
        <% if nightclub.adapted %>
            <div class="thumbnail adapted">
        <% else %>
            <div class="thumbnail not-adapted">
        <% end %>
        <a href="/nightclubs/<%= nightclub.id %>">
          <%= image_tag(nightclub.image.url(:thumbnail)) %>
          <% if nightclub.adapted %>
              <%= image_tag('/adapted-icon.png', class: 'adapted-icon') %>
          <% end %>
          <div class="caption">
            <h3> <%= nightclub.name %> </h3>
            <p> <%= nightclub.location %> </p>
          </div>
        </a>
        </div>
        </div>
  <% end %>
  </div>
</div>

app/views/nightclubs/edit.html.erb
<% if @nightclub.user != current_user %>
    <br>
    <div class="alert alert-danger text-center">
      <strong>¡Violación de permisos!</strong> <p>No posees permisos para modificar/eliminar este local.</p>
    </div>
<% else %>
    <h1>Editing Nightclub</h1>

    <%= render 'form', nightclub: @nightclub %>

    <%= link_to 'Show', @nightclub %> |
    <%= link_to 'Back', nightclubs_path %>
<% end %>

app/views/nightclubs/index.html.erb
<!-- Carousel-->
<div class="carousel-container col-md-8 col-md-offset-2" >
  <%=  render 'layouts/carousel' %>
</div>

<div class="nav-wrapper">
  <div id="affix-container" class="row spacing-navbar  clear myaffix nav" data-spy="affix">
    <%= render 'layouts/navbar' %>
  </div>
</div>

<div id="container" class="clear">
  <% @nightclubs.each do |nightclub| %>
      <div class="grid col-md-2 col-md-offset-1">
        <% if nightclub.adapted %>
            <div class="thumbnail adapted">
        <% else %>
            <div class="thumbnail not-adapted">
        <% end %>
        <a href="/nightclubs/<%= nightclub.id %>">
          <%= image_tag(nightclub.image.url(:thumbnail)) %>
          <% if nightclub.adapted %>
              <%= image_tag('/adapted-icon.png', class: 'adapted-icon') %>
          <% end %>
          <div class="caption">
            <h3> <%= nightclub.name %> </h3>
            <p> <%= nightclub.location %> </p>
          </div>
        </a>
        </div>
        </div>
  <% end %>
  </div>
</div>

app/views/nightclubs/my_nightclubs.erb
<div class="text-center">
  <%= link_to ' Añadir local', new_nightclub_path, class: "btn btn-default glyphicon glyphicon-plus" %>
</div>

<div class="row clear">
  <% @nightclubs.each do |nightclub| %>
      <div class="col-md-2 col-md-offset-1">
        <div class="thumbnail">
          <a href="/nightclubs/<%= nightclub.id %>">
            <%= image_tag(nightclub.image.url(:thumbnail)) %>
            <% if nightclub.adapted %>
                <%= image_tag('/adapted-icon.png', class: 'adapted-icon') %>
            <% end %>
            <div class="caption">
              <h3> <%= nightclub.name %> </h3>
              <p> <%= nightclub.location %> </p>
            </div>
          </a>
        </div>
      </div>
  <% end %>
</div>

app/views/nightclubs/new.html.erb
<h1>New Nightclub</h1>

<%= render 'form', nightclub: @nightclub %>

<%= link_to 'Back', nightclubs_path %>

app/views/nightclubs/show.html.erb
<div class="row clear">
  <% if @nightclub.user == current_user %>
      <div>
        <%= link_to ' Editar', edit_nightclub_path(@nightclub), class: "btn btn-default glyphicon glyphicon-pencil" %>
        <%= link_to ' Borrar', nightclub_path(@nightclub), method: :delete, data: { confirm: '¿Está seguro que quiere borrar este local?' }, class: "btn btn-default glyphicon glyphicon-trash" %>
      </div>
  <% end %>
  <!-- Image -->
  <div class="col-md-2 col-md-offset-1">
    <p>
      <%= image_tag(@nightclub.image.url(:large))%>
      <% if @nightclub.adapted %>
          <%= image_tag('/adapted-icon.png', class: 'adapted-icon') %>
      <% end %>
    </p>

    <p>
      <strong>Name:</strong>
      <%= @nightclub.name %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= @nightclub.location %>
    </p>
  </div>

  <div class="col-md-2 col-md-offset-1">
    <p>
      <strong>Price:</strong>
      <%= @nightclub.price.to_s + "€" %>
    </p>

    <p>
      <strong>Date:</strong>
      <%= @nightclub.date %>
    </p>
  </div>

  <div class="col-md-2 col-md-offset-1">
    <%= render 'map' %>
  </div>
</div>

<div class="row clear">
  <div class="col-md-4 col-md-offset-1">
    <p>
      <%= @nightclub.description %>
    </p>
  </div>
</div>

<div class="nav-wrapper">
  <div id="navbarfix" class="row clear spacing-navbar  clear myaffix nav" data-spy="affix" data-offset-top="190">
    <%= render 'layouts/navbar' %>
  </div>
</div>

<% if @nightclub.user == current_user %>
    <div>
      <%= render 'gallery_form', gallery: @gallery_and_photo.first %>
    </div>
<% end %>

<!-- Galleries -->
<div class="container">
  <div class="row clear">
    <% @nightclub.galleries.each do |gallery| %>
        <div class="col-md-2">
          <%= link_to nightclub_gallery_path(:nightclub_id => @nightclub.id)  do %>
          <div class="carousel-container-160x1250">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
              <div id="carousel-controller-fix" class="carousel-inner" role="listbox">
                <% gallery.photos.each_with_index do |photo, iteration| %>
                    <% if iteration == 0 %>
                        <div  class="item active">
                          <%= image_tag(photo.image.url(:large), class: 'carousel-img') %>
                        </div>
                    <% else %>
                        <div  class="item">
                          <%= image_tag(photo.image.url(:large), class: 'carousel-img') %>
                        </div>
                    <% end %>
                <% end %>
              </div>
          <% end %>
            </div>
            <p class="text-center"><%= gallery.created_at.strftime("%d %b. %Y") %></p>
            <% if @nightclub.user == current_user %>
                <div>
                  <%= render 'photo_form', photo: @gallery_and_photo.second, gallery_id: gallery.id %>
                </div>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
</div>