config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :photos
  resources :galleries
  resources :nightclubs do
    resources :galleries
  end
  get '/my_nightclubs' => 'nightclubs#my_nightclubs'
  resources :questions
  resources :home
  get '/adapted_nightclubs' => 'nightclubs#adapted', :as => :adapted
  match '/home' => 'home#index', via: [:get, :post]
  get 'events' => 'home#events'
  get '/photography' => 'photography#index'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :nightclub, required: true
  has_many :photos
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery.nightclub, notice: 'Galería creada exitosamente,' }
        format.json { render :show, status: :created, location: @gallery.nightclub }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:nightclub_id)
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.erb
<%= form_for(gallery) do |f| %>
  <% if gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nightclub_id %>
    <%= f.text_field :nightclub_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing Gallery</h1>

<%= render 'form', gallery: @gallery %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Galleries</h1>

<table>
  <thead>
    <tr>
      <th>Nightclub</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= gallery.nightclub %></td>
        <td><%= link_to 'Show', gallery %></td>
        <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
        <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery', new_gallery_path %>

app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= render 'form', gallery: @gallery %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<div id="photos-container">
<% @gallery.photos.each do |photo| %>
    <div class="col-md-4 img-cont">
      <%= image_tag(photo.image.url(:large), :class  => "img-full") %>
    </div>
<% end %>
</div>