config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :photos
  resources :galleries
  resources :nightclubs do
    resources :galleries
  end
  get '/my_nightclubs' => 'nightclubs#my_nightclubs'
  resources :questions
  resources :home
  get '/adapted_nightclubs' => 'nightclubs#adapted', :as => :adapted
  match '/home' => 'home#index', via: [:get, :post]
  get 'events' => 'home#events'
  get '/photography' => 'photography#index'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_carousel.html.erb
<div class="carousel-container-371x1250">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">

    <!-- Wrapper for slides -->
    <div id="carousel-controller-fix" class="carousel-inner" role="listbox">
      <div  class="item active">
        <%= image_tag('1c8e28f86c921f7b5cc4244e7a88278e4.jpg', class: 'carousel-img') %>
      </div>

      <div  class="item">
        <%= image_tag('Evento.jpg', class: 'carousel-img') %>
      </div>

      <div  class="item">
        <%= image_tag('1c8e28f86c921f7b5cc4244e7a88278e4.jpg', class: 'carousel-img') %>
      </div>

      <div  class="item">
        <%= image_tag('Evento.jpg' , class: 'carousel-img') %>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" id="control-fix"  role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel"   id="control-fix"  role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    </a>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav id="headerfix" class=" navbar navbar-inverse header col-md-12 col-lg-12 col-sm-12 ">
  <div id="left-padding-fixed" class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-header">
      <%= link_to 'CanParty',  root_url, class: "navbar-brand" %>
    </div>
    <div class="navbar-form navbar-right">
      <% if current_user %>
          <%= notice %> <%= current_user.email%>
          <%= link_to ' Mis locales',  my_nightclubs_path, class: "btn glyphicon glyphicon-th-list" %>
          <%= link_to ' Logout', destroy_user_session_path, method: :delete, class: "btn btn-default glyphicon glyphicon-off" %>
      <% else %>
          <%= notice %>
          <%= link_to ' Login', new_user_session_path, class: "btn btn-default glyphicon glyphicon-user" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav id="left-padding-fixed" class=" navbar navbar-inverse col-md-10 col-lg-10 col-sm-10 affixtarget">
  <div id="left-padding-fixed" class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div id="nav" class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="left-padding-fixed">
      <ul class="nav navbar-nav">
        <li class="li">
          <% if current_page?(nightclubs_url)%>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Filtrar Locales<span class="caret"></span></a>
              <ul class="dropdown-menu violet filters">
                <li data-filer="adapted"><%=	link_to 'Locales adaptados', adapted_path %> </li>
                <li date-filter="rent"><a href="#not-adapted">Locales en alquiler</a></li>
                <li date-filter="erasmus"><a href="#not-adapted">Locales Erasmus</a></li>
              </ul>
            </li>
        <% else %>
            <li > <%= link_to 'Locales', nightclubs_url %> </li>
        <% end %>
        </li>
        <li > <%= link_to 'Eventos',  events_path  %> </li>
        <li> <%= link_to 'Fotografía', photography_url %> </li>
        <li> <%= link_to 'FAQ', questions_url %> </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="search" class="form-control" placeholder="Buscar">
        </div>
        <button type="submit" class="btn btn-default">Buscar</button>
      </form>
    </div>
  </div>
</nav>
<nav class="navbar trigger navbar-inverse calendar col-md-2 col-lg-2 col-sm-2">
  <input type="hidden" id="datepicker">
  <div class="text-center">Calendario</div>
</nav>


<script>
  <!-- Calendar -->
  $(function () {
    $("#datepicker").datepicker("option", "dateFormat", "yy-mm-dd");
    $(".trigger").click(function () {
      $("#datepicker").datepicker("show");
    });
  });

  $("#datepicker").datepicker({
    onSelect: function(dateText) {
      console.log("Selected date: " + dateText + "; input's current value: " + this.value);

      $.ajax({
        url:'/home',
        type:'POST',
        dataType:'json',
        data:{
          myparam1: "First Param value",
          myparam2: "Second param value",
        }
      });
    }
  });

  function Resize (){
    $(".myaffix").css("width", $("#navbarfix").width());
    $("#affix-container").affix({
      offset: {
        top: $('.affixtarget').offset().top - $('.affixtarget').height()
      }
    })
  }

  Resize();
  //$(".myaffix").css("width", $(window).outerWidth(true));
  $(window).on("resize", Resize());

  $(document).on("page:change", Resize());
  $(document).ready(Resize());
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CanParty</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>
      $(function($){
        $.datepicker.regional['es'] = {
          closeText: 'Cerrar',
          prevText: '<Ant',
          nextText: 'Sig>',
          currentText: 'Hoy',
          monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
          monthNamesShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
          dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
          dayNamesShort: ['Dom','Lun','Mar','Mié','Juv','Vie','Sáb'],
          dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
          weekHeader: 'Sm',
          dateFormat: 'dd/mm/yy',
          firstDay: 1,
          isRTL: false,
          showMonthAfterYear: false,
          yearSuffix: ''
        };
        $.datepicker.setDefaults($.datepicker.regional['es']);
      });
    </script>
  </head>
  <body>
  <div id="headerfix" class="nav-wrapper">
    <div id="headerfix" class="row clear spacing-navbar  clear  nav" >
      <%= render 'layouts/header' %>
    </div>
  </div>


  <%= yield %>




  </body>
</html>